export const USER_NAME = "USER_NAME";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_DIFFICULTY = "SELECT_DIFFICULTY";
export const SELECT_TYPE = "SELECT_TYPE";
export const SELECT_NUMBER_OF_QUESTIONS = "SELECT_NUMBER_OF_QUESTIONS";
export const COUNT_SCORE = "COUNT_SCORE";
